### ISSUE TITLE
asset_path nunjucks helper function is required

### ISSUE THREAD

**Issue by r4vi** [nhsuk-archive/frontend-version-one#1]
Unable to call `asset_path`, which is undefined or falsey

need to document that the templates use an 'asset_path' helper and maybe explain:
*  how to add it to your nunjucks environment,  
* what it's supposed to do
* and especially a example naive version:
    ```options.compileOptions.environment.addGlobal('asset_path', function(path) {return path;});```

**Comment by tyom** [comment]
Added [a note in README](https://github.com/nhsuk/frontend#asset_path).

**Comment by st3v3nhunt** [comment]
Not going to be fixed.
