### ISSUE TITLE
This package needs to include base assets

### ISSUE THREAD

**Issue by r4vi** [nhsuk-archive/frontend-version-one#2]
These are referenced in the `head.njk` template but not included in the package

- assets/images/favicon-preview.png
- assets/images/favicon.png
- assets/images/opengraph-image.png
- 'css/nhsuk-' + font + '.css'
- css/nhsuk-ie6.css (and the -font- version)
- css/nhsuk-ie7.css (and the -font- version)
- css/nhsuk-ie8.css (and the -font- version)
- css/nhsuk.css
- assets/javascripts/ie.bundle.js (what's this? will all template users need this?)
- assets/javascripts/picturefill.bundle.js (are we assuming everyone wants picturefill?)

**Comment by tyom** [comment]
Good points. I'll add favicon images and logos but I think we need to think a bit more on which CSS files to include. Same with JavaScript.

Also, what do we do about fonts and licensing?

**Comment by r4vi** [comment]
I guess we can reference the fonts as strings and leave it to the app to reference the font src in its own CSS for example:

In this repo:

    body {
        font-family: fsme, Arial;
    }

in the project using this package's repo:

    @font-face {
        font-family: fsme;
        src: url(fsme.woff);
    }

**Comment by tyom** [comment]
This should be resolved in #3.
